server:
  port: 8081

base-url:
  context: /user-management-system/1.0.0
spring:
  application:
    name: user-management-system
    version: 1.0.0
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
springdoc:
  #version: '@springdoc.version@'
  #api-docs:
  #enabled: false
  swagger-ui:
    #path: /mobile-house-manage-system/1.0.0/swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true
logging:
  level:
    org:
      springframework:
        web: INFO
        hibernate: ERROR
    com: INFO
    root: INFO
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){yellow} %clr(:){red} %clr(%m){faint}%n"
    file: "%d{yy-MM-dd E HH:mm:ss.SSS } [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: C:\Users\ASUS\Documents\logs\elk-stack.log



